# Generated by Django 3.1.3 on 2024-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('comic', models.TextField(blank=True)),
            ],
        ),
    ]
